### PR TITLE
Allow encoded key of length 224

### PR DESCRIPTION
**Pull request by phuongnd08**

### CODE REVIEW

**Comment by eagleas** [comment]
Hmm... More logically - check key length AFTER decoding.
Sorry, I will rollback this pull request merge and fix code. Ok?

**Comment by phuongnd08** [comment]
Sure man :) What's ever the right code to write.

**Comment by eagleas** [comment]
Please, test code in develop branch.

**Comment by phuongnd08** [comment]
Look good, that should do. A version bump please.

**Comment by eagleas** [comment]
Look good or work good? )

**Comment by phuongnd08** [comment]
Look :)

**Comment by eagleas** [comment]
Оk, I will release 0.15 version

**Comment by eagleas** [comment]
done.

**Comment by phuongnd08** [comment]
Very cool, thank man.

**Pull request merged**
